# Generated by Django 5.2 on 2025-05-04 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumni', '0001_initial'),
        ('events', '0002_alter_events_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('registration_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registration_date', models.DateField()),
                ('status', models.CharField(max_length=25)),
                ('alumni_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.alumni')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
            ],
            options={
                'db_table': 'registrations',
            },
        ),
    ]
