# Generated by Django 5.2 on 2025-05-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('alumni_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=120)),
                ('alumni_email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=16)),
                ('graduation_year', models.DateField()),
                ('degree', models.CharField(max_length=120)),
                ('department', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'alumni',
            },
        ),
    ]
