# Generated by Django 5.2 on 2025-05-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('speaker_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('speaker_name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'speakers',
            },
        ),
    ]
