# Generated by Django 5.2 on 2025-04-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('program_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'programs',
            },
        ),
    ]
